dist: trusty
sudo: required
os:
  - linux
language: python
python:
  - 2.7.13

env:
  global:
    - CC_TEST_REPORTER_ID=db72f1ed59628c16eb0c00cbcd629c4c71f68aa1892ef42d18c7c2b8326f460a

branches:
  only:
  - master
  - /^(?!wip-).+$/

cache:
  pip: true
  directories:
  - $HOME/virtualenv/python2.7.13/lib/python2.7/site-packages
  - $HOME/virtualenv/python2.7.13/bin/

install:
  - scripts/travis_install.sh

script:
  - scripts/travis_test.sh
